<a href="https://colab.research.google.com/github/jrgrajek/Capstone/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
2+2

4

In [4]:
import torch
import numpy as np

In [5]:
my_list = [1,2,3,4,5]
my_list


[1, 2, 3, 4, 5]

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.40921475, 0.43496456, 0.52678117, 0.53228911],
       [0.15539743, 0.49480361, 0.09930017, 0.45608838],
       [0.1026043 , 0.01933556, 0.28595008, 0.28136217]])

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d = torch.zeros(3,4)
tensor_3d

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4092, 0.4350, 0.5268, 0.5323],
        [0.1554, 0.4948, 0.0993, 0.4561],
        [0.1026, 0.0193, 0.2860, 0.2814]], dtype=torch.float64)

In [10]:
my_tensor.dtype


torch.float64

In [11]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Reshape and View
my_torch= my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
# Reshape if we don't know the number of items using =1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [15]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# Differences between shape and view

In [18]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [21]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [22]:
# Slices
my_torch7 = torch.arange(10)
my_torch7


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch7[7]

tensor(7)

In [24]:
# Grab a slice

In [25]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [26]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [27]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [28]:
#4 Video Tensor Math

In [29]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [30]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [31]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [32]:
# Subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [33]:
# Sub Function

In [34]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [35]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [36]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [37]:
# Division
tensor_b/ tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [38]:
# Division Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [39]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [40]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [41]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [42]:
# Another way to add
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [48]:
# Reassignment
tensor_a + tensor_b

tensor([16, 20, 24, 28])

In [49]:
tensor_a

tensor([11, 14, 17, 20])

In [50]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([16, 20, 24, 28])

In [51]:
tensor_a

tensor([16, 20, 24, 28])